### ISSUE TITLE
some bugs about markup function

### ISSUE THREAD

**Issue by geseki** [yzyray/lizzieyzy#256]
hello
I am using lizzieyzy well
I would like to thank you again.

There is a bug and I would like to report it.

When marking on a checkerboard or stone(using squares, triangles, alphabets, numbers, etc. in markup tools) the last bottom line(19cells) and right line(19cells)cannot be marked up.

![스크린샷 2023-12-13 180838](https://github.com/yzyray/lizzieyzy/assets/32949498/11f3b10f-8555-4593-a945-423408c91da4)

**Comment by hope366** [comment]
I also noticed that bug and posted it here a while ago.
https://github.com/yzyray/lizzieyzy/issues/253
Since the developers of LizzieYzy seem to be unresponsive, we contacted the contributors of Lizzie's development.
He immediately suggested improvements.
I took the improvements and compiled LizzieYzy.
We have incorporated this improvement proposal into the latest version "2.5.3".
Please try it if you like.
https://drive.google.com/file/d/1hfZya2cNARaiX0vPUgYGBwQZQV1N5DOa/view?usp=sharing

**Comment by geseki** [comment]
Thank you very much for your help.
I really needed the markup feature.

I downloaded the Google Drive you sent me.
-- lizzie-yzy2.5.4-shaded.jar (30.4mb)

This file is written as a jar file, but in fact I
I know very little about programming.

How do I apply the jar file to my lizzieyzy?
Can you give me a quick tip?

**Comment by hope366** [comment]
I usually put the jar file in lizzieyzy's folder and double-click the jar file there. (Windows environment)
If the jar file does not start properly, please also try the exe file below.
https://drive.google.com/file/d/1NbOCk2BNCyCsj6191qMAVtU3R2kxgWYL/view?usp=sharing

**Comment by geseki** [comment]
It runs well.
The problem has been completely resolved.
Thank you very much and have a good day!

**Comment by geseki** [comment]
solved
