### ISSUE TITLE
[Suggest] What if input captured stones when start board synchronization.

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#5]
Your tool is so amazing and thank you for providing this.
Now I'm learning how to use it and got a suggestion while using it.

I hope that "Board Synchronization Tool" able to input captured stones number when it starts synchronization.
It'll make it clear for katago to score.

Thank you again for your great work.
Good luck!

<img width="359" alt="20210927_183908" src="https://user-images.githubusercontent.com/37356450/134884416-a92ee4f9-ff58-4177-8761-4a8e241dd128.png">

**Comment by yzyray** [comment]
Do you mean manually input capture stones in Synchronization Tool frame?It seems impossible to get captured stones from a board image.And if manually  input capture stones,I doublt if there is a command could tell katago engine current capture numbers.

**Comment by wonsiks** [comment]
@yzyray I've meant manually input capture stones. However I'v not thought of telling them to katago engine.

**Comment by yzyray** [comment]
The only way I could thought is not use territory in rules.For example if the game is under komi 6.5 territory  rule,use area+button+komi7.0 in katago although it is not exactly same.

**Comment by kris-computer-go** [comment]
Can you explain step by step how to use synchronization tool please. Today I was trying to match KataGo in LizzieYzy with Golaxy online in 19x19.com. I did success only in one game and every other - many many times failed.
There was a line of white / black stones on the 1st line of the board. It was very frustrating. I don't understand why there are two version of this tool: simplified and normal one.

**Comment by yzyray** [comment]
Generally only two steps,click "select board" and select the board rigion,and click "continuous sycn".
If it does not work,you can try "select row one" and select exactly row one rigion instead of "select board".
If you are using  simplified version,when selecting the board rigion,you'd better select a little bigger than the board,it maybe help with "a line of white / black stones" issue.This issue should not occoured in normal version.
Noarmal version is more convenient for fox,tygem,sina platform but can only work in windows system,simplified version can be used in linux or macos.

**Comment by yzyray** [comment]
If using Noarmal version in fox tygem sina platform,only need select right platform and click "FastSync".

**Comment by kris-computer-go** [comment]
Thank you for your explanation
